### ISSUE TITLE
Get It To Work With Python 3

### ISSUE THREAD

**Issue by ldo** [smcameron/mister-nouveau-artboto#1]
Hi. I was curious to know what your program did. First I had to patch it to work. [Enclosed](https://github.com/smcameron/mister-nouveau-artboto/files/4569790/ldo-python3.patch.txt) is a quick patch that seemed sufficient to get results out of it. ;)

**Comment by smcameron** [comment]
Thanks, applied as cc9cc0aa950504dc380af23715d4ae3ce9282eed
